source 'https://rubygems.org'
ruby "2.4.0"

gem 'aws-sdk', '~> 2'
gem 'bcrypt'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'gon-sinatra'
gem 'httparty'
gem 'pg'
gem 'pry'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'will_paginate'
gem 'resque'
